CREATE SEQUENCE IF NOT EXISTS PRODUCT_ID_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS VARIANT_ID_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS PRODUCT_TYPE (
    ID BIGINT PRIMARY KEY,
    NAME VARCHAR(120) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS PRODUCT (
    ID BIGINT PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    PRODUCT_TYPE_ID BIGINT NOT NULL,
    BODY_HTML TEXT,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    VENDOR VARCHAR(255) NOT NULL,
    CONSTRAINT FK_PRODUCT_PRODUCT_TYPE FOREIGN KEY (PRODUCT_TYPE_ID) REFERENCES PRODUCT_TYPE (ID),
    CONSTRAINT CK_PRODUCT_TITLE_NOT_BLANK CHECK (LENGTH(TRIM(TITLE)) > 0),
    CONSTRAINT CK_PRODUCT_VENDOR_NOT_BLANK CHECK (LENGTH(TRIM(VENDOR)) > 0)
);

CREATE TABLE IF NOT EXISTS VARIANT (
    ID BIGINT PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    SKU VARCHAR(255) NOT NULL,
    AVAILABLE BOOLEAN NOT NULL,
    PRICE NUMERIC(19, 2) NOT NULL,
    PRODUCT_ID BIGINT NOT NULL,
    CREATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    UPDATED_AT TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT FK_VARIANT_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID) ON DELETE CASCADE,
    CONSTRAINT CK_VARIANT_TITLE_NOT_BLANK CHECK (LENGTH(TRIM(TITLE)) > 0),
    CONSTRAINT CK_VARIANT_SKU_NOT_BLANK CHECK (LENGTH(TRIM(SKU)) > 0),
    CONSTRAINT CK_VARIANT_PRICE_RANGE CHECK (PRICE >= 0 AND PRICE <= 100000000)
);

INSERT INTO PRODUCT_TYPE (ID, NAME) SELECT 1, 'Bag' WHERE NOT EXISTS (SELECT 1 FROM PRODUCT_TYPE WHERE ID = 1);
INSERT INTO PRODUCT_TYPE (ID, NAME) SELECT 2, 'Crop Top' WHERE NOT EXISTS (SELECT 1 FROM PRODUCT_TYPE WHERE ID = 2);
INSERT INTO PRODUCT_TYPE (ID, NAME) SELECT 3, 'Jacket' WHERE NOT EXISTS (SELECT 1 FROM PRODUCT_TYPE WHERE ID = 3);
INSERT INTO PRODUCT_TYPE (ID, NAME) SELECT 4, 'Jeans' WHERE NOT EXISTS (SELECT 1 FROM PRODUCT_TYPE WHERE ID = 4);
INSERT INTO PRODUCT_TYPE (ID, NAME) SELECT 5, 'Jogger' WHERE NOT EXISTS (SELECT 1 FROM PRODUCT_TYPE WHERE ID = 5);
INSERT INTO PRODUCT_TYPE (ID, NAME) SELECT 6, 'Leggings' WHERE NOT EXISTS (SELECT 1 FROM PRODUCT_TYPE WHERE ID = 6);
INSERT INTO PRODUCT_TYPE (ID, NAME) SELECT 7, 'Long Sleeve' WHERE NOT EXISTS (SELECT 1 FROM PRODUCT_TYPE WHERE ID = 7);
INSERT INTO PRODUCT_TYPE (ID, NAME) SELECT 8, 'Shoes' WHERE NOT EXISTS (SELECT 1 FROM PRODUCT_TYPE WHERE ID = 8);
INSERT INTO PRODUCT_TYPE (ID, NAME) SELECT 9, 'Shorts' WHERE NOT EXISTS (SELECT 1 FROM PRODUCT_TYPE WHERE ID = 9);
INSERT INTO PRODUCT_TYPE (ID, NAME) SELECT 10, 'Sports Bra' WHERE NOT EXISTS (SELECT 1 FROM PRODUCT_TYPE WHERE ID = 10);
INSERT INTO PRODUCT_TYPE (ID, NAME) SELECT 11, 'Sweater' WHERE NOT EXISTS (SELECT 1 FROM PRODUCT_TYPE WHERE ID = 11);
INSERT INTO PRODUCT_TYPE (ID, NAME) SELECT 12, 'Tank Top' WHERE NOT EXISTS (SELECT 1 FROM PRODUCT_TYPE WHERE ID = 12);
INSERT INTO PRODUCT_TYPE (ID, NAME) SELECT 13, 'T-Shirt' WHERE NOT EXISTS (SELECT 1 FROM PRODUCT_TYPE WHERE ID = 13);
